// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandsMall.Data.ContextClass;

namespace PandsMall.Migrations
{
    [DbContext(typeof(PandsContext))]
    partial class PandsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PandsMall.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6778),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6796),
                            Name = "Toiletries"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6823),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6828),
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6828),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6833),
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6833),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6833),
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6837),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 419, DateTimeKind.Local).AddTicks(6837),
                            Name = "Bakeries"
                        });
                });

            modelBuilder.Entity("PandsMall.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<short>("QuantityInPackage");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 415, DateTimeKind.Local).AddTicks(4722),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(4992),
                            Name = "Delta Soap",
                            Price = 750.0,
                            QuantityInPackage = (short)6
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6346),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6364),
                            Name = "Apple",
                            Price = 500.0,
                            QuantityInPackage = (short)6
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6378),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6378),
                            Name = "Pepsi",
                            Price = 1500.0,
                            QuantityInPackage = (short)12
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6382),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6382),
                            Name = "Gas Cooker",
                            Price = 3000.0,
                            QuantityInPackage = (short)1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            DateCreated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6387),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 33, 15, 417, DateTimeKind.Local).AddTicks(6387),
                            Name = "Meat Pie",
                            Price = 300.0,
                            QuantityInPackage = (short)1
                        });
                });

            modelBuilder.Entity("PandsMall.Data.Entities.Product", b =>
                {
                    b.HasOne("PandsMall.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
