// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PandsMall.Data.ContextClass;

namespace PandsMall.Migrations
{
    [DbContext(typeof(PandsContext))]
    partial class PandsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PandsMall.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(416),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(430),
                            Name = "Toiletries"
                        },
                        new
                        {
                            Id = 2,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(452),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(452),
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = 3,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(457),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(457),
                            Name = "Drinks"
                        },
                        new
                        {
                            Id = 4,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(461),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(461),
                            Name = "Kitchen"
                        },
                        new
                        {
                            Id = 5,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(461),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 542, DateTimeKind.Local).AddTicks(466),
                            Name = "Bakeries"
                        });
                });

            modelBuilder.Entity("PandsMall.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<DateTime>("DateCreated");

                    b.Property<DateTime>("DateUpdated");

                    b.Property<string>("Name");

                    b.Property<double>("Price");

                    b.Property<short>("QuantityInPackage");

                    b.Property<byte>("UnitOfMeasurement");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 509, DateTimeKind.Local).AddTicks(3588),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(2289),
                            Name = "Delta Soap",
                            Price = 750.0,
                            QuantityInPackage = (short)6,
                            UnitOfMeasurement = (byte)3
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3489),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3503),
                            Name = "Apple",
                            Price = 500.0,
                            QuantityInPackage = (short)6,
                            UnitOfMeasurement = (byte)3
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3516),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3521),
                            Name = "Pepsi",
                            Price = 1500.0,
                            QuantityInPackage = (short)12,
                            UnitOfMeasurement = (byte)5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3521),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3525),
                            Name = "Gas Cooker",
                            Price = 3000.0,
                            QuantityInPackage = (short)1,
                            UnitOfMeasurement = (byte)4
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 5,
                            DateCreated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3525),
                            DateUpdated = new DateTime(2019, 7, 22, 11, 8, 42, 540, DateTimeKind.Local).AddTicks(3530),
                            Name = "Meat Pie",
                            Price = 300.0,
                            QuantityInPackage = (short)1,
                            UnitOfMeasurement = (byte)3
                        });
                });

            modelBuilder.Entity("PandsMall.Data.Entities.Product", b =>
                {
                    b.HasOne("PandsMall.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
